### ISSUE TITLE
Request for explanation on observer54-5

### ISSUE THREAD

**Issue by phufbq** [Philsie/ARRS-documentation#17]
Hi Philsie / contributing team,

On observer54-5, how do you utilise the keywords? REST, LAMA, TRUST, ORPHEUS.
I converted the binary to ascii characters, but the "1" note, I think converts to "iinbqsj".

I don't know how you go from "iinbqsj" -> "revizor". Especially as the first character is the same: "ii".

Am I wrong thinking it is a keyword cipher?

**Comment by Philsie** [comment]
![image](https://github.com/Philsie/ARRS-documentation/assets/46480764/bf6f580d-0057-4664-8f5c-eee2d9ccac54)

will update the file to make it clearer

**Comment by phufbq** [comment]
Thanks Philsie. Was there a hint somewhere that Vigenere cipher was to be used?

**Comment by Philsie** [comment]
Dont think so, just something we commonly use
